#!/usr/bin/env bash
# Workshop bring-up (Hot Aisle 1× MI300X path).
#
# Assumes the VM has already been provisioned via scripts/hotaisle-bring-up.sh
# AND vm-prep.sh + launch-qwen.sh have been run on the VM. This script handles
# the laptop side: open the SSH tunnel to the VM's :30000, verify SGLang
# responds, then start LiteLLM on :4000 pointed at the tunneled SGLang.
#
# Run from your laptop, not inside the VM.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/../lib/env.sh"
[ -f "$SCRIPT_DIR/../lib/env.local.sh" ] && . "$SCRIPT_DIR/../lib/env.local.sh"

preflight_laptop
require_var VM_SSH_HOST
require_var SGLANG_API_KEY

# Master key for LiteLLM. If not set in env.local.sh, mint one and persist.
if [ -z "${LITELLM_MASTER_KEY:-}" ]; then
    LITELLM_MASTER_KEY="sk-workshop-$(openssl rand -hex 16)"
    echo "" >> "$SCRIPT_DIR/../lib/env.local.sh"
    echo "# Auto-generated by bring-up.sh — workshop bearer for Claude Code clients" \
        >> "$SCRIPT_DIR/../lib/env.local.sh"
    echo "export LITELLM_MASTER_KEY='$LITELLM_MASTER_KEY'" \
        >> "$SCRIPT_DIR/../lib/env.local.sh"
    log "Minted new LITELLM_MASTER_KEY (saved to lib/env.local.sh)"
fi
export LITELLM_MASTER_KEY

LOCAL_PORT="${LOCAL_PORT:-30000}"
REMOTE_PORT="${REMOTE_PORT:-30000}"
LITELLM_PORT="${LITELLM_PORT:-4000}"
TUNNEL_PID_FILE="/tmp/hotaisle-tunnel-${LOCAL_PORT}.pid"

# Kill any prior tunnel on the same local port (idempotent re-runs)
if [ -f "$TUNNEL_PID_FILE" ] && kill -0 "$(cat "$TUNNEL_PID_FILE")" 2>/dev/null; then
    log "Closing prior tunnel pid $(cat "$TUNNEL_PID_FILE")..."
    kill "$(cat "$TUNNEL_PID_FILE")" 2>/dev/null || true
    sleep 1
fi
pkill -f "ssh -N.*-L ${LOCAL_PORT}:127.0.0.1:${REMOTE_PORT}" 2>/dev/null || true

log "Opening SSH tunnel: localhost:$LOCAL_PORT → ${VM_SSH_HOST}:${REMOTE_PORT} (background)"
nohup ssh -N \
    -o ServerAliveInterval=30 \
    -o ServerAliveCountMax=3 \
    -o ExitOnForwardFailure=yes \
    -o StrictHostKeyChecking=accept-new \
    -L "${LOCAL_PORT}:127.0.0.1:${REMOTE_PORT}" \
    -p "${VM_SSH_PORT:-22}" \
    "${VM_SSH_USER:-hotaisle}@${VM_SSH_HOST}" \
    >/tmp/hotaisle-tunnel-${LOCAL_PORT}.log 2>&1 &
TUNNEL_PID=$!
echo "$TUNNEL_PID" > "$TUNNEL_PID_FILE"
log "  tunnel pid: $TUNNEL_PID"

# Give ssh -N a moment to actually bind the local port
for _ in $(seq 1 10); do
    if curl -sf -m 2 -H "Authorization: Bearer $SGLANG_API_KEY" \
         "http://127.0.0.1:${LOCAL_PORT}/health" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

log "Verifying SGLang /health via tunnel (up to 5 min)..."
DEADLINE=$(( $(date +%s) + 5*60 ))
HEALTHY=0
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
    if curl -sf -m 5 -H "Authorization: Bearer $SGLANG_API_KEY" \
         "http://127.0.0.1:${LOCAL_PORT}/health" >/dev/null 2>&1; then
        log "  SGLang /health 200 via tunnel"
        HEALTHY=1
        break
    fi
    sleep 10
done

[ $HEALTHY -eq 1 ] || fail "SGLang not reachable through tunnel. Did you run launch-qwen.sh on the VM? Check: ssh ${VM_SSH_USER:-hotaisle}@${VM_SSH_HOST} 'docker logs --tail 80 sglang'"

# MODEL_API_BASE for LiteLLM. The proxy runs inside Docker on the laptop, so
# 127.0.0.1 from its perspective is the container itself — use host.docker.internal
# to reach the SSH tunnel listening on the laptop's :LOCAL_PORT.
export MODEL_API_BASE="http://host.docker.internal:${LOCAL_PORT}/v1"
log "  MODEL_API_BASE=$MODEL_API_BASE"

# Start LiteLLM (no plaintext secret rendered to disk; api_key resolved from env)
LITELLM_CFG="$SCRIPT_DIR/../litellm/litellm_config.yaml"
[ -f "$LITELLM_CFG" ] || fail "missing $LITELLM_CFG"

litellm_start "$LITELLM_CFG" || fail "LiteLLM failed to start"

# Verify LiteLLM exposes the configured models — Claude Code may discover them
# on connect, and this catches yaml typos / env-var misses early.
log "Verifying LiteLLM /v1/models (with master key)..."
LL_MODELS=$(curl -sf -m 5 -H "Authorization: Bearer $LITELLM_MASTER_KEY" \
    "http://127.0.0.1:${LITELLM_PORT}/v1/models" 2>/dev/null || echo "")
if ! echo "$LL_MODELS" | grep -q "qwen3.6-27b\|claude-sonnet-4-6\|claude-opus-4-7"; then
    fail "LiteLLM /v1/models missing expected aliases. Got: $(echo "$LL_MODELS" | head -c 300)"
fi
log "  LiteLLM exposes the configured Qwen aliases"

# Sanity: requests without the master key must be rejected
log "Verifying auth gate (requests without master key should be rejected)..."
LL_NO_AUTH=$(curl -sS -o /dev/null -w "%{http_code}" -m 5 \
    "http://127.0.0.1:${LITELLM_PORT}/v1/models" 2>/dev/null || echo "000")
if [ "$LL_NO_AUTH" = "200" ]; then
    fail "LiteLLM is accepting unauthenticated requests despite master_key being set"
fi
log "  unauthenticated requests rejected (HTTP $LL_NO_AUTH)"

cat <<EOF

==========================================
READY — Hot Aisle 1× MI300X / Qwen3.6-27B

Tunnel:    localhost:$LOCAL_PORT → ${VM_SSH_HOST}:${REMOTE_PORT}  (pid $TUNNEL_PID)
LiteLLM:   http://localhost:${LITELLM_PORT}
Bearer:    $LITELLM_MASTER_KEY

Set in your shell, then run claude:
  export ANTHROPIC_BASE_URL=http://localhost:${LITELLM_PORT}
  export ANTHROPIC_AUTH_TOKEN=$LITELLM_MASTER_KEY
  export CLAUDE_CODE_MAX_OUTPUT_TOKENS=8192   # cap output to fit 64k ctx
  export MAX_THINKING_TOKENS=4096             # cap reasoning budget
  claude

Watchdog:  bash $SCRIPT_DIR/watchdog.sh &
Tear down: bash $SCRIPT_DIR/hotaisle-tear-down.sh
==========================================
EOF
